import turtle
turtle.Screen().bgcolor("pink")
sc=turtle.Screen()
pointer=turtle.Turtle()
pointer.forward(100)
pointer.left(45)
pointer.forward(100)
pointer.left(50)
pointer.forward(100)
pointer.left(50)
pointer.forward(100)
pointer.left(45)
pointer.forward(100)
pointer.left(45)
pointer.forward(100)
pointer.left(45)
pointer.forward(100)
pointer.left(55)
pointer.forward(70)

turtle.done()