pasta=("Pasta Arrabiata","Italian",20,"Medium")
biryani=("Chicken Biryani","Indian",45,"Hard")
print("Recipe 1:",pasta)
print("Name:",pasta[0])
print("Cuisine:",pasta[1])
print("Difficulty:",pasta[-1])
all_recipes=(pasta,biryani)
print("\nFirst recipe name:",all_recipes[0][0])
print("second recipe time:",all_recipes[1][2],"mins")
print("Pasta details (sliced):",pasta[1:3])
print("\nPasta Recipe details:")
for detail in pasta:
    print(" -",detail)
pasta_ingredients={"tomato","garlic","onion","Olive oil","Cilli","pasta"}
biryani_ingredients={"tomato","garlic","onion","Olive oil","Salt","Rice","Chicken"}
print("\npasta ingrediedients are:",pasta_ingredients)
print("biryani ingrediedients are:",biryani_ingredients)
pasta_ingredients.add("permeasen")
pasta_ingredients.discard("chilli")
print("\nUpdated pastaingredients",pasta_ingredients)
all_ingredients=pasta_ingredients.union(biryani_ingredients)
common=pasta_ingredients.intersection(biryani_ingredients)
only_pasta=pasta_ingredients.difference(biryani_ingredients)
unique_to_each=pasta_ingredients.symmetric_difference(biryani_ingredients)
print("\nAll ingredients(union):",all_ingredients)
print("common ingredients(intersection):",common)
print("only in pasta(difference):",only_pasta)
print("unique(symmetric_diiference):",unique_to_each)