from tkinter import*
window = Tk()  
window.title("My Profile Card")
window.geometry('800x500')
lbl=Label(text="my profile card", fg="white", bg="pink", width=60 , pady=10)
lbl.pack()
name=Label(text="Name", fg="black", bg="skyblue", pady=2)
name.place(x=200,y=100)
name=Label(text="Hobby", fg="black", bg="skyblue", pady=2)
name.place(x=200,y=150)
e1=Entry(width=40,bg="lightyellow",)
e1.place(x=300,y=100)
e2=Entry(width=40,bg="lightyellow",)
e2.place(x=300,y=150)
txt=Text(height=5,width=35,bg="lightyellow")
txt.place(x=250,y=200)
btn=Button(bg="pink",text="Click me",fg="white")
btn.place(x=350,y=300)
window.mainloop()