from tkinter import*
window = Tk()  
window.title("Personal Bio Form")
window.geometry('800x500')
lbl=Label(text="Personal Bio Form ", fg="Black", bg="Skyblue", width=60 , pady=10, font="italic",)
lbl.pack()
name=Label(text="Name", fg="black", bg="Pink", pady=2)
name.place(x=100,y=50)
name=Label(text="Father Name", fg="black", bg="Pink", pady=2)
name.place(x=350,y=50)
name=Label(text="Hobby", fg="black", bg="pink", pady=2)
name.place(x=100,y=80)
e1=Entry(width=25,bg="lightyellow",)
e1.place(x=150,y=50)
e2=Entry(width=25,bg="lightyellow",)
e2.place(x=150,y=80)
e3=Entry(width=25,bg="lightyellow",)
e3.place(x=440,y=50)
window.mainloop()